### ISSUE TITLE
Add support for PHP 8.0

### ISSUE THREAD

**Issue by leafling** [elastic/site-search-php#15]
I have upgraded to PHP 8.0 and noticed this package doesn't currently officially support it.

I was able to install elastic/site-search-php under PHP 8.0 with:

`composer update --ignore-platform-reqs`

and it seems to work fine.  I didn't run any tests beyond dropping it in and testing it on my site, but assuming it passes any other tests you may want to run, I think it should be as easy as changing line 17 of the composer.json file to add support for PHP 8.0 here:

https://github.com/elastic/site-search-php/blob/master/composer.json

to from:
`"php" : "^5.6|^7.0",`
to
`"php" : "^5.6|^7.0|^8.0",`

This wouldn't correct the issue I reported earlier with it using the abandoned guzzle packages, but it would at least allow it to install on PHP 8.0 without composer complaining or needing the  --ignore-platform-reqs flag.

Can you please add support for PHP 8.0?  (and potentially add updates to support modern guzzle packages?

Thanks!

**Comment by amineSt** [comment]
+1

**Comment by amineSt** [comment]
Hello, i am waiting for this PR https://github.com/elastic/openapi-codegen-php/pull/15 to open one for this package.

Thank you.

**Comment by leafling** [comment]
Has this package been deprecated? It hasn't seen any updates since it was created 4+ years ago and can no longer be readily installed with modern version of PHP without using the "--ignore-platform-reqs" (which appears to work fine) 

However, now as I try to install it with Laravel 10, I get additional conflicts base on legacy dependencies in the chain that require an old version of monolog.  I'd love to see this package (and elastic controlled dependencies) updated to use modern packages/dependencies. We've been happy with the swiftype site-search product, but this package appears to get zero attention from elastic.  I wouldn't think the necessary updates should take that much effort to modernize dependencies.  

If this package is not going to see updates, it would be nice to flag it as deprecated and let your users be aware of that intent, but as of now this remains the recommended PHP API Client for Swiftype's Site Search product as it is listed on their "Official Swiftype Site Search Client Libraries" page here: https://swiftype.com/documentation/site-search/clients

**Comment by liranabn** [comment]
Thank you for reporting this issue. We appreciate your feedback and we are currently evaluating the effort required to support PHP 8.X.
Thanks for your patience.

**Comment by phptek** [comment]
> Thank you for reporting this issue. We appreciate your feedback and we are currently evaluating the effort required to support PHP 8.X. Thanks for your patience.

Any update on this?

**Comment by tutelaris** [comment]
The PHP 8 version has been bumped. Thank you for opening the issue
