### ISSUE TITLE
PHP client should throw an exception / response for rate limit (429)

### ISSUE THREAD

**Issue by romain-chanu** [elastic/site-search-php#8]
## Background
As a user, I want to handle 429 errors received by the server and implement a retry mechanism.

## Problem
As of today, the `site-search-php` throws a [general exception](https://github.com/elastic/site-search-php/blob/9e03671f813f18d9e3baa04bd2f99b554d0d0eb3/Connection/Handler/ApiErrorHandler.php) for 429 error code without any response details regarding the rate limit. Based on the [documentation](https://swiftype.com/documentation/site-search/rate_limiting), there are two response headers which provide a guideline towards the rate limit. Without information related to the rate limit, the caller cannot implement such retry mechanism.

## Possible solution
Similiar to the [app-search-php](https://github.com/elastic/app-search-php/blob/db3cdb50983a5212a77cdc0b2dd28c506c79652d/Exception/ApiRateExceededException.php) client, the `site-search-php` client could also return a specific exception so that the caller can handle rate limit.

**Comment by afoucret** [comment]
PR #8 fix this issue.
An exception (`\Elastic\SiteSearch\Client\Exception\ApiRateExceededException`)  is thrown when the request is rate limited.

Additionally, a warning is logged (if using a logger) on every request when the consumed rate limit percentage is over 90% for the request type.
